### ISSUE TITLE
Vitestが通らない

### ISSUE THREAD

**Issue by knarimatsu** [knarimatsu/kabukeisan_fe#131]
```
bun run test
```
を実行
```
$ vitest
/kabukeisan_fe/node_modules/rollup/dist/native.js:59
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/kabukeisan_fe/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/kabukeisan_fe/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-x64'
  Require stack:
  - /kabukeisan_fe/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
      at Module._load (node:internal/modules/cjs/loader:990:27)
      at Module.require (node:internal/modules/cjs/loader:1237:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/kabukeisan_fe/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/kabukeisan_fe/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1378:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
      at Module.load (node:internal/modules/cjs/loader:1212:32)
      at Module._load (node:internal/modules/cjs/loader:1028:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/kabukeisan_fe/node_modules/rollup/dist/native.js'
    ]
  }

```
こんなエラーが出ている

**Comment by knarimatsu** [comment]
とりあえず、vitestのバージョンとかみてみるか、、、

**Comment by knarimatsu** [comment]
解決の方法がこれであっているかわからないがうまく通るようになった
```
rm -rf node_modules
rm bun.lockb
npm i
```
